### ISSUE TITLE
rtdl: linker does not enter directories

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/mlibc#80] opened 2020-05-08 20:51 UTC
Under Linux, libraries in subdirs of `/usr/lib`, for example, `man-db` in `/usr/lib/man-db`, are found and used as requested. When running managarm, the libraries in these directories are not found, and need to be copied over manually to `/usr/lib`.

Tested with `man-db's` `man` command

**Comment by avdgrinten** [comment] 2020-05-09 08:19
Hm, I think Linux has a cache of DSO paths. I don't know how exactly it works but that's something we need to look into.

**Comment by Dennisbonke** [comment] 2020-06-14 23:21
seems that this is fixed, at least for man-db by pr #92? I'll leave it open in case it isn't properly fixed

**Comment by 64** [comment] 2022-07-06 01:25
I think this might be some other bug, because on my system `man` sets RPATH to `/usr/lib/man-db/`.

Can we check that this still reproduces on mlibc master?

**Comment by 64** [comment] 2022-07-06 03:50
Yeah, `man` works fine for me on managarm, so I'm going to close this.

**Closed by 64** 2022-07-06 03:50 UTC
Labels: bug
